[package]
name = "rsloop-rust-example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
name = "rsloop_rust_example"

[dependencies]
async-std = "1"
pyo3 = "0.29.2"
rsloop = { path = "../.." }

[profile.release]
opt-level = 3
lto = "fat"
incremental = false
codegen-units = 1
# strip = true
